apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: artist-api
  description: Retrieve artist details
  annotations:
  'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=petclinic'
spec:
  type: openapi
  lifecycle: production
  owner: artist-team
  system: artist-topia
  definition: |
    openapi: "3.0.0"
    info:
      version: 2.0.0
      title: Artist API
      license:
        name: MIT
    servers:
      - url: http://artist.spotify.net/v1
    paths:
      /artists:
        get:
          summary: List all artists version 2
    groupId: artists-group-api

